// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClx33Pk_BJgyGunN94BRVgEE2LwpnUFDk',
    appId: '1:428886003775:web:f22148b83a153d9185288a',
    messagingSenderId: '428886003775',
    projectId: 'littleimmune',
    authDomain: 'littleimmune.firebaseapp.com',
    storageBucket: 'littleimmune.appspot.com',
    measurementId: 'G-6SPL9EN7S0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACDy3CNA7reM5PhN_zXNobu68yzIrmMes',
    appId: '1:428886003775:android:dc45a2fdb2125c9385288a',
    messagingSenderId: '428886003775',
    projectId: 'littleimmune',
    storageBucket: 'littleimmune.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVL2Ny1_XfOkGa9qDGzRalcZA1CY5jNkw',
    appId: '1:428886003775:ios:2a9854bdcf9959bc85288a',
    messagingSenderId: '428886003775',
    projectId: 'littleimmune',
    storageBucket: 'littleimmune.appspot.com',
    iosClientId: '428886003775-pmmcu22gcvt4opog4jrb4gcn1o2nheha.apps.googleusercontent.com',
    iosBundleId: 'com.example.littleImmune',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVL2Ny1_XfOkGa9qDGzRalcZA1CY5jNkw',
    appId: '1:428886003775:ios:2a9854bdcf9959bc85288a',
    messagingSenderId: '428886003775',
    projectId: 'littleimmune',
    storageBucket: 'littleimmune.appspot.com',
    iosClientId: '428886003775-pmmcu22gcvt4opog4jrb4gcn1o2nheha.apps.googleusercontent.com',
    iosBundleId: 'com.example.littleImmune',
  );
}
